#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       sailfishweibopy

# >> macros
%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
# << macros

%define sailfishweibo /usr/share/harbour-sailfish_sinaweibo
%define pycurl  /usr/share/doc/pycurl

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}

Summary:    login module for SailfishWeibo
Version:    0.2
Release:    1
Group:      Python
License:    LGPL
URL:        https://github.com/SunRain/SailfishWeibo
Source0:    %{name}-%{version}.tar.bz2
#Source100:  sailfishweibopy.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   openssl-libs
Requires:   libcurl
Requires:   pyotherside-qml-plugin-python3-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  python3-devel
BuildRequires:  gcc
BuildRequires:  libcurl-devel
BuildRequires:  openssl-devel

%description
login module for SailfishWeibo


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
export PYCURL_SSL_LIBRARY=openssl
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%postun
rm -rf /usr/lib/python3.4/site-packages/curl
rm -rf /usr/lib/python3.4/site-packages/pycurl*

%files
%defattr(-,root,root,-)
/usr/lib/python3.4/site-packages/*
%{sailfishweibo}
# >> files
# << files
